Fix & Add tags titles.
anidl/funimation-downloader-nx pull request #101
Opened 2021-08-29 15:59 UTC by OryWareKyrie

Addition of Simulcast and Uncut to the track titles. in case simulcast uses ```--simul``` by default Uncut is used.
Valeu pela ajuda vovó @alfablac :smiley_cat:

2021-08-29 19:40 UTC, izu-co requested changes
Hello there. 

First, many thanks for going to the trouble of programming an extension to this tool.

There are some things I have to request to be changed, before I can merge this PR, however.

 - Why did you delete the `package-lock.json` file?'
 - I think your code base is not up-to-date (haven't checked, just a feeling)?
 - Lastly, there are a lot of style changes in the files. Is there a particular reason for that?

2021-08-29 20:34 UTC, OryWareKyrie commented
> Hello there.
> 
> First, many thanks for going to the trouble of programming an extension to this tool.
> 
> There are some things I have to request to be changed, before I can merge this PR, however.
> 
> * Why did you delete the `package-lock.json` file?'
> * I think your code base is not up-to-date (haven't checked, just a feeling)?
> * Lastly, there are a lot of style changes in the files. Is there a particular reason for that?
> 
> There are some conflicts by the way that `must` be resolved before I can even merge it :).

bro I honestly don't know what happened. even to prevent this, I took the most recent version of the code, anidl, and made the changes to it. I think when formatting the files with eslint I have deleted something. I formatted all the documents.

2021-08-30 11:00 UTC, izu-co commented
izu [this](https://github.com/anidl/funimation-downloader-nx/blob/master/config/cli-defaults.yml#L1) line has some function in the tool? 🤔

Not anymore

2021-08-30 11:05 UTC, izu-co requested changes

2021-08-30 11:05 UTC, izu-co commented on config/cli-defaults.yml
> +muxSubs: true
You can remove this line since it isn't used anymore

2021-08-30 11:05 UTC, izu-co commented on modules/module.getdata.js
> +        gOptions.headers['User-Agent'] = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0';
These changes are already in the newest version, are they not?

2021-08-30 12:15 UTC, izu-co commented
@OryWareKyrie I think it would be best if you apply your changes to a fork of this repo and not my fork. 

I think it would save a lot of trouble.

2021-09-01 11:31 UTC, OryWareKyrie commented
> @OryWareKyrie I think it would be best if you apply your changes to a fork of this repo and not my fork.
> 
> I think it would save a lot of trouble.

I think I will do this even izu :smile_cat:

2021-09-01 11:31 UTC, closed without merging